trigger:
  branches:
    include:
    - main
  paths:
    include:
    - TodoApi

pool:
  name: default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '7.x'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'TodoApi/*.csproj'
    arguments: '-c $(buildConfiguration)'

# Run unit tests
- task: DotNetCoreCLI@2
  displayName: Unit Test
  inputs:
    command: test
    projects: '*ApiTest/*.csproj'
    arguments: '-c $(buildConfiguration)'

# Run code coverage
- task: DotNetCoreCLI@2
  displayName: Code Coverage
  inputs:
    command: test
    projects: '*ApiTest/*.csproj'
    arguments: '-c $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'TodoApi/*.csproj'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to Azure
  inputs:
    azureSubscription: 'AZURE_SUBSCRIPTION'
    appType: 'webApp'
    appName: 'wv-todos-api'
    package: '$(Build.ArtifactStagingDirectory)/TodoApi.zip'